<div class="modal fade" id="commentaireModal" tabindex="-1" role="dialog" aria-labelledby="commentaireModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="actu_commentaire"></h4>
      </div>
      <div class="modal-body">
        <form id="form_commentaire">
          <div class="form-group" >
              <span id="id_actu" hidden/></span>
            <label for="recipient-name" class="control-label">Auteur :</label>
            <input type="text" class="form-control" id="auteur_commentaire">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Commentaire :</label>
            <textarea class="form-control" id="contenu_commentaire"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-default" data-dismiss="modal">Fermer</button>
        <button type="submit" id="envoi_commentaire" data-dismiss="modal" class="btn btn-primary">Envoyer le commentaire</button>
      </div>
    </div>
  </div>
</div>