<!-- AFFICHE LA LISTE DES COMMENTAIRES -->
<ul class="media-list">
    <?php foreach ($this->comment->fetchall() as $comment) :?>
    <li class="media">
       
        <div class="media-left">
        
        </div>
        <div class="media-body">
          <h4 class="media-heading"><?=$comment->auteur?></h4>
          <?=$comment->commentaire?>
        </div>
        <div class="media-right">
          
                      
            <?=$comment->date?>

        </div>
    </li>
     <?php endforeach;?>
</ul>